- requirements.txt: updated for "pre-push" tests
- simple_consensus_caller: minimap/2.17 is required. 2.15 fails

- EXAMPLE FAILS: python rnn_consensus_infer.py --infer-hdf infer.hdf --model-dir `pwd`/sample_models -o sample.fasta

  File "rnn_consensus_infer.py", line 101, in <module>
    infer(args)
  File "rnn_consensus_infer.py", line 78, in infer
    fastq_file.write_output("dl_consensus", nucleotides_sequence, nucleotides_certainty)
  File "/home/UNIXHOME/mbrown/mbrown/workspace2020Q3/VariantWorks/VariantWorks/variantworks/io/fastxio.py", line 70, in write_output
    convert_error_probability_arr_to_phred([1 - val for val in record_quality])
  File "/home/UNIXHOME/mbrown/mbrown/workspace2020Q3/VariantWorks/VariantWorks/variantworks/utils/metrics.py", line 25, in convert_error_probability_arr_to_phred
    raise ValueError("all values in error probability array must be between 0 and 1")
   ValueError: all values in error probability array must be between 0 and 1

  - TODO: Bug? All values are negative. Softmaxes vs probablitiies?
    See comments in samples/simple_consensus_caller/rnn_consensus_infer.py